# Generated by Django 5.0.6 on 2024-06-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_user_password_commonexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='daily_spending_limit',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_money',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=10),
        ),
    ]
