# Generated by Django 5.0.6 on 2024-06-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_alter_user_daily_spending_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.CharField(choices=[('meal', 'Meal'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('groceries', 'Groceries'), ('transportation', 'Transportation'), ('insurance', 'Insurance'), ('healthcare', 'Healthcare'), ('entertainment', 'Entertainment'), ('education', 'Education'), ('savings', 'Savings'), ('debt_repayment', 'Debt Repayment'), ('clothing', 'Clothing'), ('personal_care', 'Personal Care'), ('pets', 'Pets'), ('subscriptions', 'Subscriptions'), ('miscellaneous', 'Miscellaneous')], default='miscellaneous', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='upiId',
            field=models.EmailField(max_length=30, null=True),
        ),
    ]
