# Generated by Django 5.0.6 on 2024-06-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_payment_description_payment_upiid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='remain_daily_target_amt',
            field=models.IntegerField(default=0),
        ),
    ]
